// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deploy.proto

package deploy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Deploy struct {
	ServerID             uint32   `protobuf:"varint,1,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	HttpAddr             string   `protobuf:"bytes,2,opt,name=HttpAddr,proto3" json:"HttpAddr,omitempty"`
	SendLimit            uint32   `protobuf:"varint,3,opt,name=SendLimit,proto3" json:"SendLimit,omitempty"`
	RecvLimit            uint32   `protobuf:"varint,4,opt,name=RecvLimit,proto3" json:"RecvLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Deploy) Reset()         { *m = Deploy{} }
func (m *Deploy) String() string { return proto.CompactTextString(m) }
func (*Deploy) ProtoMessage()    {}
func (*Deploy) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f09e103004e384, []int{0}
}

func (m *Deploy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deploy.Unmarshal(m, b)
}
func (m *Deploy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deploy.Marshal(b, m, deterministic)
}
func (m *Deploy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deploy.Merge(m, src)
}
func (m *Deploy) XXX_Size() int {
	return xxx_messageInfo_Deploy.Size(m)
}
func (m *Deploy) XXX_DiscardUnknown() {
	xxx_messageInfo_Deploy.DiscardUnknown(m)
}

var xxx_messageInfo_Deploy proto.InternalMessageInfo

func (m *Deploy) GetServerID() uint32 {
	if m != nil {
		return m.ServerID
	}
	return 0
}

func (m *Deploy) GetHttpAddr() string {
	if m != nil {
		return m.HttpAddr
	}
	return ""
}

func (m *Deploy) GetSendLimit() uint32 {
	if m != nil {
		return m.SendLimit
	}
	return 0
}

func (m *Deploy) GetRecvLimit() uint32 {
	if m != nil {
		return m.RecvLimit
	}
	return 0
}

func init() {
	proto.RegisterType((*Deploy)(nil), "deploy.Deploy")
}

func init() { proto.RegisterFile("deploy.proto", fileDescriptor_05f09e103004e384) }

var fileDescriptor_05f09e103004e384 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x49, 0x2d, 0xc8,
	0xc9, 0xaf, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x6a, 0xb8, 0xd8,
	0x5c, 0xc0, 0x2c, 0x21, 0x29, 0x2e, 0x8e, 0xe0, 0xd4, 0xa2, 0xb2, 0xd4, 0x22, 0x4f, 0x17, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xde, 0x20, 0x38, 0x1f, 0x24, 0xe7, 0x51, 0x52, 0x52, 0xe0, 0x98, 0x92,
	0x52, 0x24, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe7, 0x0b, 0xc9, 0x70, 0x71, 0x06, 0xa7,
	0xe6, 0xa5, 0xf8, 0x64, 0xe6, 0x66, 0x96, 0x48, 0x30, 0x83, 0x35, 0x22, 0x04, 0x40, 0xb2, 0x41,
	0xa9, 0xc9, 0x65, 0x10, 0x59, 0x16, 0x88, 0x2c, 0x5c, 0x20, 0x89, 0x0d, 0xec, 0x18, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x86, 0xf7, 0xd8, 0x9c, 0x00, 0x00, 0x00,
}
